# Generated by Django 5.2.6 on 2025-09-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_remove_pessoa_altura_remove_pessoa_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
